#!/usr/bin/env perl
use v5.10;
use strict;
use warnings;
use Win32::TieRegistry;

my $INSTALL = "C:\\Program Files\\tom";
if ( -e $INSTALL ) {
    say "It looks like tom is already installed.";
}
else {
    say "==> Installing tom...";
    system "cmd.exe /K xcopy /S . \"$INSTALL\" && exit";
    say '--> DONE.';
}

$INSTALL =~ s/\\/\\\\/g;
if ( grep { /$INSTALL/ } split /;/, $ENV{PATH} ) {
    say "It looks like tom is already in your PATH";
}
else {
    say "==> Adding tom to system path...";
    my $key  = 'HKEY_CURRENT_USER\\Environment\\PATH';
    my $path = $Registry->{$key};
    $Registry->{$key} = "$path;$INSTALL";
    say "- DONE.";
}
